/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef dc_agent_CONSTANTS_H
#define dc_agent_CONSTANTS_H

#include "dc_agent_types.h"

namespace dc {

class dc_agentConstants {
 public:
  dc_agentConstants();

};

extern const dc_agentConstants g_dc_agent_constants;

} // namespace

#endif
