/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "dc_agent_constants.h"

namespace dc {

const dc_agentConstants g_dc_agent_constants;

dc_agentConstants::dc_agentConstants() {
}

} // namespace

