// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "DcAgent.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::dc;

class DcAgentHandler : virtual public DcAgentIf {
 public:
  DcAgentHandler() {
    // Your initialization goes here
  }

  void run(std::string& _return, const std::string& command) {
    // Your implementation goes here
    printf("run\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<DcAgentHandler> handler(new DcAgentHandler());
  shared_ptr<TProcessor> processor(new DcAgentProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

