/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef DcAgent_H
#define DcAgent_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "dc_agent_types.h"

namespace dc {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class DcAgentIf {
 public:
  virtual ~DcAgentIf() {}
  virtual void run(std::string& _return, const std::string& command) = 0;
};

class DcAgentIfFactory {
 public:
  typedef DcAgentIf Handler;

  virtual ~DcAgentIfFactory() {}

  virtual DcAgentIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(DcAgentIf* /* handler */) = 0;
};

class DcAgentIfSingletonFactory : virtual public DcAgentIfFactory {
 public:
  DcAgentIfSingletonFactory(const boost::shared_ptr<DcAgentIf>& iface) : iface_(iface) {}
  virtual ~DcAgentIfSingletonFactory() {}

  virtual DcAgentIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(DcAgentIf* /* handler */) {}

 protected:
  boost::shared_ptr<DcAgentIf> iface_;
};

class DcAgentNull : virtual public DcAgentIf {
 public:
  virtual ~DcAgentNull() {}
  void run(std::string& /* _return */, const std::string& /* command */) {
    return;
  }
};

typedef struct _DcAgent_run_args__isset {
  _DcAgent_run_args__isset() : command(false) {}
  bool command :1;
} _DcAgent_run_args__isset;

class DcAgent_run_args {
 public:

  DcAgent_run_args(const DcAgent_run_args&);
  DcAgent_run_args& operator=(const DcAgent_run_args&);
  DcAgent_run_args() : command() {
  }

  virtual ~DcAgent_run_args() throw();
  std::string command;

  _DcAgent_run_args__isset __isset;

  void __set_command(const std::string& val);

  bool operator == (const DcAgent_run_args & rhs) const
  {
    if (!(command == rhs.command))
      return false;
    return true;
  }
  bool operator != (const DcAgent_run_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DcAgent_run_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class DcAgent_run_pargs {
 public:


  virtual ~DcAgent_run_pargs() throw();
  const std::string* command;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DcAgent_run_result__isset {
  _DcAgent_run_result__isset() : success(false) {}
  bool success :1;
} _DcAgent_run_result__isset;

class DcAgent_run_result {
 public:

  DcAgent_run_result(const DcAgent_run_result&);
  DcAgent_run_result& operator=(const DcAgent_run_result&);
  DcAgent_run_result() : success() {
  }

  virtual ~DcAgent_run_result() throw();
  std::string success;

  _DcAgent_run_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const DcAgent_run_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const DcAgent_run_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const DcAgent_run_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _DcAgent_run_presult__isset {
  _DcAgent_run_presult__isset() : success(false) {}
  bool success :1;
} _DcAgent_run_presult__isset;

class DcAgent_run_presult {
 public:


  virtual ~DcAgent_run_presult() throw();
  std::string* success;

  _DcAgent_run_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class DcAgentClient : virtual public DcAgentIf {
 public:
  DcAgentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  DcAgentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void run(std::string& _return, const std::string& command);
  void send_run(const std::string& command);
  void recv_run(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class DcAgentProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<DcAgentIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (DcAgentProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_run(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  DcAgentProcessor(boost::shared_ptr<DcAgentIf> iface) :
    iface_(iface) {
    processMap_["run"] = &DcAgentProcessor::process_run;
  }

  virtual ~DcAgentProcessor() {}
};

class DcAgentProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  DcAgentProcessorFactory(const ::boost::shared_ptr< DcAgentIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< DcAgentIfFactory > handlerFactory_;
};

class DcAgentMultiface : virtual public DcAgentIf {
 public:
  DcAgentMultiface(std::vector<boost::shared_ptr<DcAgentIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~DcAgentMultiface() {}
 protected:
  std::vector<boost::shared_ptr<DcAgentIf> > ifaces_;
  DcAgentMultiface() {}
  void add(boost::shared_ptr<DcAgentIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void run(std::string& _return, const std::string& command) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->run(_return, command);
    }
    ifaces_[i]->run(_return, command);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class DcAgentConcurrentClient : virtual public DcAgentIf {
 public:
  DcAgentConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  DcAgentConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void run(std::string& _return, const std::string& command);
  int32_t send_run(const std::string& command);
  void recv_run(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
